### ISSUE TITLE
Achieve working deployment on Beaglebone

### ISSUE THREAD

**Issue by evallen** [autoboat-vt/OLD-sailbot-21#50]
We need to make sure our entire codebase as a whole can be deployed onto the Beaglebone and can run (all threads operational / running as placeholders).

**Comment by evallen** [comment]
Waiting on the wifi-module to get back to test out automated deployment; local deployment to the Beaglebone seems to be working for now as far as actually transferring the code.

**Comment by evallen** [comment]
Beaglebone can successfully begin execution of the main code. Looks like there's some old things that have changed (like this error:)
```
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main()
  File "main.py", line 27, in main
    Sail = sail.SailListener(boat, world)
  File "/sailbot/src/sail/sail_listener.py", line 12, in __init__
    pub.subscribe(self.trim_boom_to, "set trim")
AttributeError: 'SailListener' object has no attribute 'trim_boom_to'
```
However, this should hopefully be easy to fix. 
I did realize I couldn't run the `main.py` method on my own computer because it tries to interface with Beaglebone-specific things (like `/dev/ttyO1`, a specific serial port on the Beaglebone for the AirMar). We probably should figure out a way to deal with that.

**Comment by evallen** [comment]
Deployment is currently very slow, taking about 5 minutes or so to transfer the Docker zip to the Beaglebone and another 5 minutes or so to run `sudo make load`. We might be able to do this faster - have to look into this more.
